

import { Translation, Language } from './types';

export const SUPPORT_NUMBER = "201557704781";

// Google Apps Script Web App URL for contact form submission - REMOVED, NOW HANDLED BY BACKEND
// export const GOOGLE_SCRIPT_URL = "https://script.google.com/macros/s/AKfycbydraEQUUGoCrvPFFY69x99XLOUTtY3VAa3gs3Pni28113Fd6rR6GmOsCWRmTl8bR-7/exec"; 

export const WEBSITE_PAGES = [
  "Home", "About Us", "Services", "Contact", "Portfolio", "Blog", "Team", "Pricing", "FAQ", "Testimonials"
];

export const TRANSLATIONS: Record<Language, Translation> = {
  en: {
    title: "Get Design AI",
    subtitle: "Select a category to generate professional designs powered by AI.",
    cat_graphics: "Graphic Design",
    cat_web: "Website Design",
    select_type: "What do you want to design?",
    type_logo: "Design Logo",
    type_identity: "Brand Identity",
    type_social: "Social Media",
    type_brochure: "Brochure/Catalog",
    type_web: "Website Design",
    tab_upload: "Upload Logo",
    tab_describe: "Describe Business",
    input_name: "Business Name",
    input_industry: "Industry",
    input_description: "Project Details",
    input_pages: "Select Pages (Max 5)",
    input_brochure_settings: "Brochure Settings",
    input_orientation: "Orientation",
    orientation_portrait: "Portrait",
    orientation_landscape: "Landscape",
    input_size: "Size / Format",
    size_a4: "A4 Standard",
    size_a5: "A5 Compact",
    size_square: "Square",
    size_folded: "Tri-Fold Flyer",
    input_page_count: "Number of Pages (Max 12)",
    upload_label: "Click to upload existing logo (PNG/JPG)",
    upload_brochure_label: "Upload Brochure/Content (Optional)",
    generate_btn: "Generate Design",
    generating: "AI Designer is creating your masterpiece...",
    download_btn: "Download High Resolution",
    canva_btn: "Edit in Canva",
    source_file_msg: "Want the editable source files?", 
    whatsapp_btn: "Request Files via WhatsApp",
    error_missing_key: "Unexpected error.",
    error_generic: "Something went wrong. Please try again.",
    placeholder_name: "e.g. TechFlow",
    placeholder_industry: "e.g. Technology, Real Estate",
    placeholder_description: "Briefly describe your business activity...",
    footer_rights: "© 2024 Get Design. All rights reserved.",
    back_to_menu: "Back to Menu",
    my_creations: "My Creations",
    no_creations: "No designs generated yet.",
    load_design: "Edit / Regenerate",
    delete_design: "Delete",
    contact_modal_title: "Almost There!",
    contact_modal_subtitle: "Please provide your contact details to start the generation process.",
    contact_name: "Full Name",
    contact_company: "Company Name",
    contact_email: "Email Address",
    contact_phone: "Phone Number",
    contact_submit: "Continue to Generation",
    validation_name_req: "Full Name is required.",
    validation_company_req: "Company Name is required.",
    validation_email: "Please enter a valid email address.",
    validation_email_req: "Email Address is required.",
    validation_phone: "Please enter a valid phone number.",
    validation_phone_req: "Phone Number is required.",
    // Sharing
    share_title: "Share your design",
    share_text_template: "Wow, I made this so quickly using getdesign.cloud. Check it out and make your own designs fast!",
    share_native_btn: "Share with your colleagues",
    share_whatsapp: "WhatsApp",
    share_linkedin: "LinkedIn",
    share_facebook: "Facebook",
    share_copied: "Link Copied!",
    // New Inputs
    input_logo_style: "Logo Style",
    style_3d: "3D Realistic",
    style_flat: "Flat / Minimal",
    input_social_platform: "Platform",
    platform_instagram: "Instagram Post (Square)",
    platform_facebook: "Facebook Cover",
    platform_linkedin: "LinkedIn Banner",
    // Color & Vibe
    input_color_vibe: "Color Direction", // Changed from Color Mood / Palette
    input_custom_colors: "Custom Colors (e.g., #FF0000, 'Ocean Blue', 'Warm Gold')",
    placeholder_custom_colors: "e.g. #7bc143, #0a0a0a, pure white; or 'vibrant blue', 'earthy green'",
    input_visual_style: "Design Style",
    style_minimalist: "Minimalist",
    style_bold: "Bold & Loud",
    style_elegant: "Elegant Serif",
    style_playful: "Playful",
    style_futuristic: "Futuristic",
    // Post Content
    input_post_content: "Marketing Message / Post Text",
    placeholder_post_content: "e.g. 50% OFF This Weekend Only!",
    // Zip Upload
    input_mode_toggle: "Design Input Method",
    mode_form_input: "Manual Form Input",
    mode_zip_upload: "Upload Zip File (Auto-Extract)",
    upload_zip_label: "Click to upload ZIP file with assets",
    zip_uploaded_msg: "Zip file loaded! (Content will be extracted by AI)",
    zip_upload_hint: "Include logo.png, brief.txt, brochure.jpg for best results.",
    validation_zip_req: "Please upload a zip file or switch to manual input.",
    result_template_link: "Find Similar Templates",
    // Admin Dashboard
    admin_login_title: "Admin Login",
    admin_username: "Username (Email)",
    admin_password: "Password",
    admin_login_btn: "Access Dashboard",
    admin_invalid_credentials: "Invalid Credentials",
    admin_leads_title: "Leads Data",
    admin_designs_title: "Generated Designs",
    admin_refresh: "Refresh Data",
    admin_logout: "Logout",
    admin_no_leads: "No leads found.",
    admin_no_designs: "No designs found.",
    admin_search_email: "Search by Email",
    admin_search_phone: "Search by Phone",
    admin_tab_leads: "Leads",
    admin_tab_designs: "Designs",
    admin_col_date: "Date",
    admin_col_name: "Name",
    admin_col_company: "Company",
    admin_col_email: "Email",
    admin_col_phone: "Phone",
    admin_col_interest: "Interest",
    admin_col_design_type: "Type",
    admin_col_business_name: "Business Name",
    admin_col_image: "Image",
    admin_col_template: "Template",
    // New Template Management Strings
    admin_tab_templates: "Templates",
    admin_no_templates: "No templates found.",
    admin_add_template: "Add New Template",
    admin_edit_template: "Edit Template",
    admin_delete_template: "Delete Template",
    admin_template_form_title_add: "Create New Conceptual Template",
    admin_template_form_title_edit: "Edit Conceptual Template",
    admin_template_id: "Template ID (Unique)",
    admin_template_type: "Design Type",
    admin_template_visual_style: "Visual Style",
    admin_template_industry_keywords: "Industry Keywords (comma-separated)",
    admin_template_prompt_hint: "Prompt Hint",
    admin_template_thumbnail_url: "Thumbnail URL (Direct Image Link)",
    admin_template_generated_content: "Generated Content Examples (JSON)",
    admin_template_save: "Save Template",
    admin_template_cancel: "Cancel",
    admin_col_id: "ID",
    admin_col_type: "Type",
    admin_col_style: "Style",
    admin_col_keywords: "Keywords",
    admin_col_prompt: "Prompt Hint",
    admin_col_thumbnail: "Thumbnail",
    admin_col_examples: "Content Examples",
    admin_template_delete_confirm: "Are you sure you want to delete this template? This action cannot be undone.",
  },
  ar: {
    title: "جيت ديزاين AI",
    subtitle: "اختر فئة لتوليد تصميمات احترافية مدعومة بالذكاء الاصطناعي.",
    cat_graphics: "تصميم جرافيك",
    cat_web: "تصميم مواقع",
    select_type: "ماذا تريد أن تصمم؟",
    type_logo: "تصميم شعار",
    type_identity: "هوية بصرية",
    type_social: "منشورات تواصل اجتماعي",
    type_brochure: "تصميم بروشور/كتالوج",
    type_web: "تصميم موقع إلكتروني",
    tab_upload: "رفع الشعار",
    tab_describe: "وصف العمل",
    input_name: "اسم النشاط التجاري",
    input_industry: "المجال/الصناعة",
    input_description: "تفاصيل المشروع",
    input_pages: "اختر الصفحات (حد أقصى 5)",
    input_brochure_settings: "إعدادات البروشور",
    input_orientation: "الاتجاه",
    orientation_portrait: "رأسي (Portrait)",
    orientation_landscape: "أفقي (Landscape)",
    input_size: "المقاس / التنسيق",
    size_a4: "A4 قياسي",
    size_a5: "A5 صغير",
    size_square: "مربع",
    size_folded: "مطوية (Tri-Fold)",
    input_page_count: "عدد الصفحات (حد أقصى 12)",
    upload_label: "اضغط لرفع شعار موجود (PNG/JPG)",
    upload_brochure_label: "رفع بروشور/محتوى (اختياري)",
    generate_btn: "توليد التصميم",
    generating: "المصمم الذكي يقوم بإنشاء التحفة الفنية...",
    download_btn: "تحميل بدقة عالية",
    canva_btn: "تعديل في Canva",
    source_file_msg: "هل تريد ملفات التصميم المفتوحة؟", 
    whatsapp_btn: "طلب الملفات عبر واتساب",
    error_missing_key: "حدث خطأ ما",
    error_generic: "حدث خطأ ما. حاول مرة أخرى.",
    placeholder_name: "مثال: تك فلو",
    placeholder_industry: "مثال: تكنولوجيا، عقارات",
    placeholder_description: "اشرح طبيعة عملك باختصار...",
    footer_rights: "© 2024 Get Design. جميع الحقوق محفوظة.",
    back_to_menu: "العودة للقائمة",
    my_creations: "تصميماتي",
    no_creations: "لم يتم إنشاء أي تصميمات بعد.",
    load_design: "تعديل / إعادة إنشاء",
    delete_design: "حذف",
    contact_modal_title: "خطوة أخيرة!",
    contact_modal_subtitle: "يرجى إدخال بيانات الاتصال للبدء في عملية التوليد.",
    contact_name: "الاسم بالكامل",
    contact_company: "اسم الشركة",
    contact_email: "البريد الإلكتروني",
    contact_phone: "رقم الهاتف",
    contact_submit: "متابعة التوليد",
    validation_name_req: "الاسم بالكامل مطلوب.",
    validation_company_req: "اسم الشركة مطلوب.",
    validation_email: "يرجى إدخال بريد إلكتروني صحيح.",
    validation_email_req: "البريد الإلكتروني مطلوب.",
    validation_phone: "يرجى إدخال رقم هاتف صحيح.",
    validation_phone_req: "رقم الهاتف مطلوب.",
    // Sharing
    share_title: "شارك تصميمك",
    share_text_template: "Wow, I made this so quickly using getdesign.cloud. Check it out and make your own designs fast!",
    share_native_btn: "مشاركة مع الزملاء",
    share_whatsapp: "واتساب",
    share_linkedin: "لينكد إن",
    share_facebook: "فيسبوك",
    share_copied: "تم نسخ الرابط!",
    // New Inputs
    input_logo_style: "نمط الشعار",
    style_3d: "ثلاثي الأبعاد (3D)",
    style_flat: "مسطح / بسيط (Flat)",
    input_social_platform: "المنصة",
    platform_instagram: "منشور انستجرام (مربع)",
    platform_facebook: "غلاف فيسبوك",
    platform_linkedin: "بانر لينكد إن",
    // Color & Vibe
    input_color_vibe: "اتجاه الألوان", // Changed from نظام الألوان
    input_custom_colors: "ألوان مخصصة (مثال: #FF0000، 'أزرق المحيط'، 'ذهبي دافئ')",
    placeholder_custom_colors: "مثال: #7bc143، #0a0a0a، أبيض نقي؛ أو 'أزرق حيوي'، 'أخضر ترابي'",
    input_visual_style: "أسلوب التصميم",
    style_minimalist: "بسيط (Minimalist)",
    style_bold: "جريء وقوي",
    style_elegant: "أنيق (Elegant)",
    style_playful: "مرح",
    style_futuristic: "مستقبلي",
    // Post Content
    input_post_content: "نص المنشور / الرسالة التسويقية",
    placeholder_post_content: "مثال: خصم ٥٠٪ لفترة محدودة!",
    // Zip Upload
    input_mode_toggle: "طريقة إدخال التصميم",
    mode_form_input: "إدخال يدوي",
    mode_zip_upload: "رفع ملف مضغوط (استخراج تلقائي)",
    upload_zip_label: "اضغط لرفع ملف ZIP مع الأصول",
    zip_uploaded_msg: "تم رفع ملف Zip! (سيتم استخراج المحتوى بواسطة الذكاء الاصطناعي)",
    zip_upload_hint: "لأفضل النتائج، قم بتضمين logo.png، brief.txt، brochure.jpg.",
    validation_zip_req: "يرجى رفع ملف مضغوط أو التبديل إلى الإدخال اليدوي.",
    result_template_link: "البحث عن قوالب مماثلة",
    // Admin Dashboard
    admin_login_title: "تسجيل دخول المسؤول",
    admin_username: "اسم المستخدم (البريد الإلكتروني)",
    admin_password: "كلمة المرور",
    admin_login_btn: "الوصول إلى لوحة التحكم",
    admin_invalid_credentials: "بيانات الاعتماد غير صالحة",
    admin_leads_title: "بيانات العملاء المحتملين",
    admin_designs_title: "التصميمات التي تم إنشاؤها",
    admin_refresh: "تحديث البيانات",
    admin_logout: "تسجيل الخروج",
    admin_no_leads: "لم يتم العثور على عملاء محتملين.",
    admin_no_designs: "لم يتم العثور على تصميمات.",
    admin_search_email: "البحث بالبريد الإلكتروني",
    admin_search_phone: "البحث برقم الهاتف",
    admin_tab_leads: "العملاء المحتملون",
    admin_tab_designs: "التصميمات",
    admin_col_date: "التاريخ",
    admin_col_name: "الاسم",
    admin_col_company: "الشركة",
    admin_col_email: "البريد الإلكتروني",
    admin_col_phone: "الهاتف",
    admin_col_interest: "الاهتمام",
    admin_col_design_type: "النوع",
    admin_col_business_name: "اسم النشاط التجاري",
    admin_col_image: "الصورة",
    admin_col_template: "القالب",
    // New Template Management Strings
    admin_tab_templates: "القوالب",
    admin_no_templates: "لم يتم العثور على قوالب.",
    admin_add_template: "إضافة قالب جديد",
    admin_edit_template: "تعديل القالب",
    admin_delete_template: "حذف القالب",
    admin_template_form_title_add: "إنشاء قالب مفاهيمي جديد",
    admin_template_form_title_edit: "تعديل القالب المفاهيمي",
    admin_template_id: "معرف القالب (فريد)",
    admin_template_type: "نوع التصميم",
    admin_template_visual_style: "النمط المرئي",
    admin_template_industry_keywords: "كلمات مفتاحية للمجال (مفصولة بفاصلة)",
    admin_template_prompt_hint: "تلميح للذكاء الاصطناعي",
    admin_template_thumbnail_url: "رابط الصورة المصغرة (رابط مباشر)",
    admin_template_generated_content: "أمثلة المحتوى المتولد (JSON)",
    admin_template_save: "حفظ القالب",
    admin_template_cancel: "إلغاء",
    admin_col_id: "المعرف",
    admin_col_type: "النوع",
    admin_col_style: "النمط",
    admin_col_keywords: "كلمات مفتاحية",
    admin_col_prompt: "تلميح",
    admin_col_thumbnail: "صورة مصغرة",
    admin_col_examples: "أمثلة المحتوى",
    admin_template_delete_confirm: "هل أنت متأكد أنك تريد حذف هذا القالب؟ لا يمكن التراجع عن هذا الإجراء.",
  }
};